logging:
  level:
    reator:
      netty:
        channel: DEBUG

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  security:
    user:
      password: '{bcrypt}$2a$10$CWPeQSrrgSCGsfnEU1G/cOfRb3NWj2TYC8L4Ln2.HKg2j3WMmPJuS'
users-url: http://localhost:8081/users
messages-url: http://localhost:8082/messages