logging:
  level:
    reator:
      netty:
        channel: DEBUG

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://idp:9999/auth/realms/demo
        registration:
          keycloak:
            client-id: spring-security
            client-secret: bfbd9f62-02ce-4638-a370-80d45514bd0a
users-url: http://localhost:8081/users
messages-url: http://localhost:8082/messages